# Generated by Django 5.0.1 on 2024-02-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About_US', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
