# Generated by Django 5.0.1 on 2024-02-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[('Draft', 'Draft'), (1, 'Published')], default='Draft', max_length=20),
        ),
    ]
