# Generated by Django 5.0.1 on 2024-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(upload_to='upload/%Y/%M/%D/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=250),
        ),
    ]
